[functions]
    # Sets the directory for the locations of Netlify functions.
    directory = "functions/"

    # Specifies `esbuild` for functions bundling.
    node_bundler = "esbuild"

[build]
    # Default build command.
    command = "npm run ci+cd"
    